"""Legal obligation and risk extraction module."""

from src.extraction.models import (
    Actor,
    Clause,
    ClauseComparison,
    ClauseLocation,
    ChangeType,
    Condition,
    ConditionType,
    Deadline,
    DeadlineType,
    DocumentComparison,
    Evidence,
    ExtractionResult,
    Favorability,
    Obligation,
    Right,
    Risk,
    RiskCategory,
    RiskLevel,
    SeverityLevel,
    TextChange,
)
from src.extraction.obligation_extractor import ObligationExtractor
from src.extraction.patterns import (
    ConditionPatterns,
    DeadlinePatterns,
    ObligationPatterns,
    PenaltyPatterns,
    RightPatterns,
)

__all__ = [
    "Actor",
    "Clause",
    "ClauseComparison",
    "ClauseLocation",
    "ChangeType",
    "Condition",
    "ConditionType",
    "Deadline",
    "DeadlineType",
    "DocumentComparison",
    "Evidence",
    "ExtractionResult",
    "Favorability",
    "Obligation",
    "Right",
    "Risk",
    "RiskCategory",
    "RiskLevel",
    "SeverityLevel",
    "TextChange",
    "ObligationExtractor",
    "ConditionPatterns",
    "DeadlinePatterns",
    "ObligationPatterns",
    "PenaltyPatterns",
    "RightPatterns",
]
